on:
  workflow_call:
    inputs:
      JDK_VENDOR:
        type: string
        description: "JDK vendor to use for build"
        required: false
        default: "corretto"
      JDK_VERSION:
        type: string
        description: "JDK version to use for build"
        required: true

jobs:
  build-test:
    runs-on: "ubuntu-latest"
    services:
      knotdns:
        image: "cznic/knot:3.4"
        ports:
          - "5353:5353"
        volumes:
          - "${{ github.workspace }}/src/test/resources/knotdns:/var/lib/knotd"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Set up JDK"
        uses: "actions/setup-java@v4"
        with:
          distribution: "${{ inputs.JDK_VENDOR }}"
          java-version: "${{ inputs.JDK_VERSION }}"
      - name: "Cache local Maven repository"
        uses: "actions/cache@v4"
        with:
          path: "~/.m2/repository"
          key: "${{ runner.os }}-hotspot-maven-${{ inputs.JDK_VENDOR }}-${{ inputs.JDK_VERSION }}-${{ hashFiles('src/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-hotspot-maven-${{ inputs.JDK_VENDOR }}-${{ inputs.JDK_VERSION }}-
      - name: "Build and test"
        run: |
          set -euo pipefail
          export VERSION="git-$(date +'%Y%m%d%H%M')-$(git rev-parse --short HEAD)"

          export KNOTDNS_CI="localhost:5353"
          export JAVAIOTMPDIR="$(pwd)/.github/tmpdir"
          chmod -v -R 0777 "$JAVAIOTMPDIR"

          mvn -B -e -fae --show-version -T$(nproc)C -Drevision="$VERSION" -DsurefireTmpDir="$(pwd)/.github/tmpdir" verify package

          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
      - name: "Archive jarfile"
        uses: "actions/upload-artifact@v4"
        with:
          name: "mcw.jar"
          path: "target/mcw.jar"
