on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]
  workflow_dispatch: { }

jobs:
  build-hotspot:
    uses: "./.github/workflows/build-hotspot.yml"
    secrets: "inherit" # for Docker image publication
    with:
      JDK_VERSION: "23"
