on:
  workflow_call:
    inputs:
      JDK_VERSION:
        type: string
        description: "JDK version to use for build"
        required: true
      BUILD_IMAGE:
        type: string
        description: "Build image"
        required: true
      BUILD_REVISION:
        type: string
        description: "Build revision"
        required: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Set up JDK"
        uses: "actions/setup-java@v4"
        with:
          distribution: "corretto"
          java-version: "${{ inputs.JDK_VERSION }}"
      - name: "Cache local Maven repository"
        uses: "actions/cache@v4"
        with:
          path: "~/.m2/repository"
          key: "${{ runner.os }}-hotspot-${{ inputs.JDK_VERSION }}-${{ hashFiles('pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-hotspot-${{ inputs.JDK_VERSION }}-
      - name: "Build and test"
        run: |
          set -euo pipefail
          mvn -B -e -fae --show-version -Drevision="${{ inputs.BUILD_REVISION }}" -DsurefireTmpDir="$(pwd)/.github/tmpdir" verify package
          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
      - name: "Archive jarfile"
        uses: "actions/upload-artifact@v4"
        with:
          name: "mcw.jar"
          path: "target/mcw.jar"
