on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        required: true
      ARTIFACT_NAME:
        type: string
        required: true
      DOCKER_REGISTRY:
        type: string
        required: true
      DOCKER_IMAGE:
        type: string
        required: true
      DOCKER_TARGET:
        type: string
        required: true
      DOCKER_TAG_CANONICAL:
        type: string
        required: true
      DOCKER_TAG_SHORT:
        type: string
        required: true

name: "Publish"
concurrency:
  group: "${{ inputs.DOCKER_TAG_CANONICAL }}-${{ inputs.DOCKER_TARGET }}"

env:
  DOCKER_LAYER_CACHE: "/tmp/.buildx-cache"

jobs:
  docker:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          persist-credentials: false
      - name: "Download artifact"
        uses: "actions/download-artifact@v4"
        with:
          name: "${{ inputs.ARTIFACT_NAME }}"
          path: "${{ github.workspace }}/target"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v3"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Cache Docker layers"
        uses: "actions/cache@v4"
        with:
          path: "${{ env.DOCKER_LAYER_CACHE }}"
          key: "${{ runner.os }}-${{ inputs.DOCKER_TARGET }}-${{ github.sha }}"
          restore-keys: |
            ${{ runner.os }}-${{ inputs.DOCKER_TARGET }}-
      - name: "Log in to the Container registry"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ inputs.DOCKER_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: "${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_IMAGE }}"
          tags: |
            type=raw,event=push,enable=true,value=${{ inputs.DOCKER_TAG_CANONICAL }}-${{ inputs.DOCKER_TARGET }}
            type=raw,event=push,enable={{ is_default_branch }},value=${{ inputs.DOCKER_TAG_SHORT }}-${{ inputs.DOCKER_TARGET }}
      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v5"
        with:
          context: "."
          push: "true"
          platforms: "linux/amd64"
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: "${{ inputs.DOCKER_TARGET }}"
          build-args: |
            JAVA_VERSION=${{ inputs.JAVA_VERSION }}
          cache-from: "type=local,src=${{ env.DOCKER_LAYER_CACHE }}"
          cache-to: "type=local,dest=${{ env.DOCKER_LAYER_CACHE }}"
